### ISSUE TITLE
Behavior of sl clone with empty basename differs from git clone

### ISSUE THREAD

**Issue by gyroninja** [facebook/sapling#828]
$ git clone https://github.com/facebook/sapling/

Clones sapling into a new directory named sapling

$ sl clone https://github.com/facebook/sapling/

Clones sapling into the current directory

I find the behavior of git to be more intuitive. I encountered this when trying to follow the build commands for another project and swapping out git for sl.

**Comment by sggutier** [comment]
Thanks for reporting this @gyroninja . As a workaround you can avoid adding the last `/` and then it should automatically create a directory with the name of the repo, e.g.,

```
$ sl clone https://github.com/facebook/sapling
```

**Comment by gyroninja** [comment]
It looks like I typed my original post. Yes, leaving off the / makes it work correctly.

**Comment by sggutier** [comment]
70c4b54f7e5c8c5a3630e233365d1cc0d55e17d6 should solve this

**Comment by gyroninja** [comment]
Unless there is some path normalization going on there is still not parity with that commit on "https://github.com/facebook/sapling//'

**Comment by sggutier** [comment]
Ah, good point
